### ISSUE TITLE
Unable to run `yarn codegen` script

### ISSUE THREAD

**Issue by ltfschoen** [mstable/mStable-app#164]
**Describe the bug**
Unable to run `yarn codegen` without error

**To Reproduce**
1. Follow the "Prerequisites" and "Installation" steps of the README
2. At the `yarn codegen` step, it generates this errorr
```
ts-gen: 💎 All done! Generated files: 211
$ graphql-codegen --config ./codegen.yml -r dotenv/config
  ✖ Parse configuration
    → Invalid Codegen Configuration!
    Generate outputs
  Invalid Codegen Configuration!

        Please make sure that your codegen config file contains either the "schema" field 
        or every generated file has its own "schema" field.
        
        It should looks like that:
        schema:
          - my-schema.graphql

        or:
        generates:
          path/to/output:
            schema: my-schema.graphql
      
Error: Invalid Codegen Configuration!
    at normalize (/Users/ls/code/src/ltfschoen/mStable-app/node_modules/@graphql-codegen/cli/bin.js:712:19)
    at Task.task (/Users/ls/code/src/ltfschoen/mStable-app/node_modules/@graphql-codegen/cli/bin.js:729:21)
    at Promise.resolve.then.then.skipped (/Users/ls/code/src/ltfschoen/mStable-app/node_modules/listr/lib/task.js:167:30)
Invalid Codegen Configuration!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Expect it to run `yarn codegen` without error

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by JamesLefrere** [comment]
Hi @ltfschoen , I think I see what the issue is here: the `.env` file needs to be populated, because it contains GraphQL endpoints required for `graphql-codegen`. I'll update the README to mention this :+1:

**Comment by ltfschoen** [comment]
Great thanks, I think I need it as I'm trying to do this bounty https://gitcoin.co/issue/mstable/mStable-app/148/100023530

**Comment by JamesLefrere** [comment]
Great! You should be good to go now @ltfschoen :)

**Comment by Yihen** [comment]
has this question  been solved?  I have met again.
