### ISSUE TITLE
Mint app not functioning as documented.

### ISSUE THREAD

**Issue by ariegrossman** [mstable/mStable-app#365]
Opened the mint app. Deposited 1000 USDC and clicked on mint.
Transaction was successful:  0x75e17bc109de52125e22e436c63008e5a1c988c6f7e7d21db0e8aefdeacdabf6
but no mUSD was minted. wallet shows starting balance of USDC and it looks like the transaction cost of this to do nothing was 0.005927509 ETH.

**Comment by chrisjgf** [comment]
The transaction posted is just the token approval transaction. To mint mUSD, you first need to approve USDC to be spent (the above tx) & then call mint (another tx)
